language: python
matrix:
  include:
    - os: linux
      sudo: required
      python: 2.7
    - os: linux
      sudo: required
      python: 3.4
    - os: linux
      sudo: required
      python: 3.6
    - os: linux
      sudo: required
      python: pypy
script:
  - make test
branches:
  only:
  - master
